corona-datenplattform:
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDk5NDkxNTcsImp0aSI6ImFMVGJudGlzQ1MtSHVGWi15R2IyWGZTZ082VUptWldZVG9ZbFZJc2RMNFEifQ.fNtAZJVhB1UZAF7ecY8E_1s15zWU19HXkHHHTD2l5Sg
  basicURL: https://www.corona-datenplattform.de/api/3/action/datastore_search?

corona-datenplattform-tabel:
  kr_massnahmen_index_monat: 23e25743-85c5-4dc8-8639-8bb11c339b19
